### ISSUE TITLE
Plugin should be signed (experimental and release)

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#10]
**Reported by Artur Signell on 5 Oct 2009 08:09 UTC**
The newest Eclipse version Galileo SR1 complains that plugins (Vaadin and others) are not signed. Check what it would require to sign the plugins and get rid of the warning.

**Comment by makoivis** [comment]
**Comment by Henri Sara on 5 Oct 2009 08:33 UTC**
To sign the plugin, the build script should run jarsigner on both the feature JAR(s) and the plugin JAR(s). For more information and examples, see e.g.:
- http://www.ibm.com/developerworks/opensource/library/os-eclipse-plugin-sigs/index.html
- http://ispras.linux-foundation.org/index.php/How_to_sign_LSB_Eclipse_Plugin

Simply signing with a self-generated key would still produce a warning, indicating that the plugin is signed but untrusted. Using a code signing certificate from a generally trusted CA (e.g. !VeriSign) should allow getting rid of the warning altogether.

**Comment by makoivis** [comment]
**Comment by Artur Signell on 5 Oct 2009 10:03 UTC**
We'll leave it unsigned for now as we do not have a certificate available and all other plugins seem to be unsigned too.

**Comment by makoivis** [comment]
**Comment by Artur Signell on 3 May 2010 11:56 UTC**
A certificate is now available, reopening and scheduling for next version.

**Comment by makoivis** [comment]
**Comment by Artur Signell on 21 Oct 2010 15:32 UTC**
Plugins are signed starting from version 1.3.0.201010211515
Wysiwyg plugin from version 0.6.0.201010211521

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:42 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 9 Sep 2014 08:39 UTC**

**Comment by hesara** [comment]
Duplicate of issue #151
