### ISSUE TITLE
Should the liferay-plugin-package.properties file be created for portlets?

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#11]
**Reported by Teemu Pontelin on 7 Oct 2009 08:20 UTC**
Currently the Eclipse plugin doesn't create the `liferay-plugin-package.properties` file for portlet projects. 

Should this file be created and should it automatically contain a dependency to the `vaadin.jar`? If I understood correctly, this is the correct way of defining a dependency to Vaadin.

```
...
portal-dependency-jars=\
    vaadin.jar
...
```

**Comment by makoivis** [comment]
**Comment by Joonas Lehtinen on 7 Oct 2009 10:39 UTC**
Should this be fixed in plugin 1.0? (Move back if not)

**Comment by makoivis** [comment]
**Comment by Artur Signell on 8 Oct 2009 05:01 UTC**
It should if vaadin.jar is installed in Liferay but what happens if the vaadin.jar is not part of Liferay?

**Comment by makoivis** [comment]
**Comment by Henri Sara on 8 Oct 2009 07:22 UTC**
Fixed in [9133]: always create the file.

This seems to work even if vaadin.jar is not in the Liferay shared directory if there is a Vaadin JAR in the portlet itself.

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:42 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 9 Sep 2014 08:39 UTC**

**Comment by hesara** [comment]
Duplicate of #152 (already closed)
