### ISSUE TITLE
Add mapping for /VAADIN/* to web.xml in portlet projects

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#12]
**Reported by Artur Signell on 8 Oct 2009 09:38 UTC**
If Vaadin is not integrated into the Liferay portal then the widgetset is not found as only "/MyServlet/_" is mapped to the servlet. The portlet tries to load the widgetset from "/portletcontextpath/VAADIN/" so a mapping for "/VAADIN/_" must be added to web.xml (when creating a portlet).

This also enables deploying the portlet project to a servlet container without modifications. 

If Vaadin is integrated into the portal then this extra mapping is just never used.

**Comment by makoivis** [comment]
**Modified by Artur Signell on 8 Oct 2009 09:39 UTC**

**Comment by makoivis** [comment]
**Modified by Teemu Pontelin on 8 Oct 2009 09:48 UTC**

**Comment by makoivis** [comment]
**Comment by Henri Sara on 8 Oct 2009 10:02 UTC**
Added in [(1.0 branch) and [9143](9141]) (trunk) for new portlet projects.

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:41 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 9 Sep 2014 08:39 UTC**

**Comment by hesara** [comment]
Duplicate of #153 (already closed)
