### ISSUE TITLE
Eclipse plugin should be off-line installable

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#13]
**Reported by Joonas Lehtinen on 21 Oct 2009 17:42 UTC**
We should have Eclipse plugin install site downloadable as zip and ensure that the plugin works without going online. 

Some reasons:
- http://vaadin.com/forum/-/message_boards/message/77339
- Distributing Vaadin on some media
- Training sessions where there is no guarantee of working network
- Archiving old versions

**Comment by makoivis** [comment]
**Modified by Artur Signell on 5 Nov 2009 06:48 UTC**

**Comment by makoivis** [comment]
**Modified by Joonas Lehtinen on 9 Nov 2009 07:04 UTC**

**Comment by makoivis** [comment]
**Comment by Artur Signell on 9 Nov 2009 10:55 UTC**
For this to work we need to include Vaadin and GWT in the plugin itself. This should be doable by allowing the plugin to search the plugin location for these files in addition to the standard download location.

The offline installable plugin thus need to be packaged separately from the update site plugin and must be updated for every new Vaadin release. This should be handled by a separate build configuration.

**Comment by makoivis** [comment]
**Modified by Artur Signell on 15 Mar 2010 12:31 UTC**

**Comment by makoivis** [comment]
**Comment by Artur Signell on 15 Oct 2010 08:21 UTC**
What should be required:
- Build configuration that packages the plugin as a Vaadin add-on: "Vaadin Eclipse Integration"
  - Add-on can be installed using Eclipse's "Install new software" -> Add -> Archive
  - Add-on includes 
  - Eclipse plugin
  - Eclipse feature 
  - Local update site 
  - From the latest release version of Vaadin
  - vaadin.jar
  - gwt-user.jar
  - gwt-dev.jar
- Eclipse plugin update 
  - Search for Vaadin versions in the plugin directory and copy them to the local store
- Update to release procedures so a new add-on is built whenever a release is made

**Comment by makoivis** [comment]
**Comment by Artur Signell on 21 Oct 2010 08:03 UTC**
Actually a better way would be to create a separate "Vaadin Jar Bundle" plugin that on installation copies the bundled Vaadin and GWT jars to the local store. This plugin should be included only in the add-on and not put on the normal update site.

**Comment by makoivis** [comment]
**Comment by Artur Signell on 26 Oct 2010 12:55 UTC**
Implemented as a separate "com.vaadin.integration.eclipse.jarbundle" plugin:
- http://dev.vaadin.com/svn/integration/eclipse/features/com.vaadin.integration.eclipse.jarbundle
- http://dev.vaadin.com/svn/integration/eclipse/plugins/com.vaadin.integration.eclipse.jarbundle

The build configuration for the plugin automatically downloads the latest stable Vaadin version and its GWT dependencies and includes them. The other included plugins (integration, wysiwyg, BoV) are downloaded from the stable update site and included in the package.

Still waiting for a Directory update so it accept this large add-ons (50MB).

**Comment by makoivis** [comment]
**Comment by Artur Signell on 2 Nov 2010 07:28 UTC**
Directory updated, all remaining is a release.

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:42 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 9 Sep 2014 08:39 UTC**

**Comment by hesara** [comment]
Duplicate of #154 (already closed)
