### ISSUE TITLE
Plugin fails to download 6.2.0 style nightly versions

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#14]
**Reported by Artur Signell on 22 Oct 2009 06:58 UTC**
The error is simply "Failed to download selected Vaadin version". A more descriptive error would be nice, for instance showing the URL that was used.

**Comment by makoivis** [comment]
**Comment by Henri Sara on 22 Oct 2009 10:42 UTC**
Fixed in [9308].

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:41 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 9 Sep 2014 08:39 UTC**

**Comment by hesara** [comment]
Duplicate of #155 (already closed)
