### ISSUE TITLE
Parameters for the widgetset builder

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#15]
**Reported by Artur Signell on 22 Oct 2009 10:27 UTC**
It must be possible to give parameters to the widgetset builder.
Most important currently would be "style" to enable building of non-obfuscated widgetsets.

**Comment by makoivis** [comment]
**Comment by Artur Signell on 25 Oct 2009 14:06 UTC**
Also it would be very useful during development to be able to easily choose to compile for a single browser.

**Comment by makoivis** [comment]
**Comment by Joonas Lehtinen on 26 Oct 2009 08:36 UTC**
Added proposed parameters..

**Comment by makoivis** [comment]
**Modified by Artur Signell on 26 Oct 2009 10:28 UTC**

**Comment by makoivis** [comment]
**Comment by Henri Sara on 4 Nov 2009 13:31 UTC**
Support for selecting code style and number of worker threads in [9625].

**Comment by makoivis** [comment]
**Comment by Henri Sara on 5 Nov 2009 07:55 UTC**
Document in the widgetset itself how to compile for one widgetset only: [(6.2 WidgetSetBuilder), [9628](9627]) (Eclipse plugin for Vaadin 6.2 widgetsets) and [(Eclipse plugin for Vaadin 6.1 and earlier widgetsets).

Added a comment about this in the plugin project property page in [9629](9629]).

Managing permutations directly through a property page would be complicated to make work reliably and of limited additional benefit. It would also need to be managed for each widgetset separately, not by project.

Considering this documentation sufficient, closing the ticket.

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:42 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 9 Sep 2014 08:39 UTC**

**Comment by hesara** [comment]
Duplicate of #156 (already closed)
