### ISSUE TITLE
Widgetset builder uses wrong java version

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#16]
**Reported by Artur Signell on 22 Oct 2009 10:28 UTC**
It should use the java version from the project, not the workspace.

**Comment by makoivis** [comment]
**Comment by Henri Sara on 26 Oct 2009 12:05 UTC**
Fixed in [9373]: use the Java VM install of the project if defined.
Also use the project VM when creating a build widgetset launch for older projects.

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:41 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 9 Sep 2014 08:39 UTC**

**Comment by hesara** [comment]
Duplicate of #157 (already closed)
