### ISSUE TITLE
Widgetset builder must be much better at finding the project

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#17]
**Reported by Artur Signell on 22 Oct 2009 10:29 UTC**
Currently you have to select the project or the widgetset.gwt.xml. It should be possible to build when anything in the project (Java file, resource,...) is selected.

**Comment by makoivis** [comment]
**Comment by Henri Sara on 23 Oct 2009 13:32 UTC**
In [9341], try to find the correct widgetset file or project from different kinds of selection, or the active editor if no suitable selection is found.

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:41 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 9 Sep 2014 08:39 UTC**

**Comment by hesara** [comment]
Duplicate of #158 (already closed)
