### ISSUE TITLE
Create a widgetset exporter

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#18]
**Reported by Artur Signell on 22 Oct 2009 10:37 UTC**
The jar export function in Eclipse is very confusing. Additionally there is no good way to specify the metadata using that and editing the manifest by hand is tedious.

Create a simple widgetset exporter that offers
- A file selector
  - Pre-select the most common values, i.e. src+classes
- A manifest editor for the Vaadin attributes
  - Manifest file
    - The user can select a MANIFEST.MF to use if he has other metadata
    - Otherwise the default is <webcontentdir>/META-INF/MANIFEST.MF
    - Changing manifest values in the editor updates the manifest file in the project.
    - No pre-existing data must be removed from the manifest
    - Existing Vaadin-attributes are used as defaults in the editor

**Comment by makoivis** [comment]
**Comment by Henri Sara on 28 Oct 2009 11:57 UTC**
Initial implementation in [9429] - does not list widgetsets in the manifest.

**Comment by makoivis** [comment]
**Comment by Henri Sara on 29 Oct 2009 08:36 UTC**
In [9431], basic support for letting the user edit the widgetsets line of the manifest

The widgetset list is presented to the user as text and - if not present in the manifest - is filled by default with the list of all widgetsets in the project.

**Comment by makoivis** [comment]
**Comment by Henri Sara on 29 Oct 2009 08:37 UTC**
Correction to the previous comment: the revision number is [9448].

**Comment by makoivis** [comment]
**Comment by Henri Sara on 29 Oct 2009 11:25 UTC**
In [9458], exclude extra copy of META-INF from defaults.

**Comment by makoivis** [comment]
**Comment by Henri Sara on 29 Oct 2009 11:44 UTC**
In [9460], fixed the overwrite checkbox.

**Comment by makoivis** [comment]
**Comment by Henri Sara on 30 Oct 2009 09:25 UTC**
In [9493], export Java files correctly.

**Comment by makoivis** [comment]
**Comment by Henri Sara on 30 Oct 2009 11:46 UTC**
Better question message for updating the manifest in [9506].

**Comment by makoivis** [comment]
**Comment by Henri Sara on 2 Nov 2009 08:52 UTC**
Considered done - any further issues should be reported as separate tickets.

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:41 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 9 Sep 2014 08:39 UTC**

**Comment by hesara** [comment]
Duplicate of #159 (already closed)
