### ISSUE TITLE
The widgetset should be built automatically

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#19]
**Reported by Artur Signell on 22 Oct 2009 10:40 UTC**
Currently there is a popup asking "Do you want to build" when you add a jar to the project. If you edit widgets in the project you must build the widgetset manually using the build icon in the toolbar. This is not nearly the optimal solution. What options do we have? I would say most commonly you want to build the widgetset before/when:
- Exporting the project 
- Publishing the project to a server
- At any random time (still provide the build button for this)
  Exporting the project (to a Directory package) is done using the exporter (#3572) so it should be easy to hook into. For publishing there are probably extension points that can be used.

Comments or better solutions?

**Comment by makoivis** [comment]
**Comment by Matti Tahvonen on 23 Oct 2009 06:54 UTC**
Note that exporting to VaadinAddon does not need a compiled widgetset. Just when exporting to war file for deployment.

**Comment by makoivis** [comment]
**Comment by Henri Sara on 3 Nov 2009 09:39 UTC**
This required keeping track of whether the widgetset is dirty or not and better management of concurrent widgetset builds.

In [9599], implemented dirty flag in project settings and a mechanism to ask about compiling the widgetset when publishing the project on a server.

To investigate if we should also do the same when exporting a WAR.

**Comment by makoivis** [comment]
**Comment by Henri Sara on 3 Nov 2009 12:48 UTC**
In [9603], fixes for dirty flag handling and Vaadin project creation (Ganymede) to avoid showing unnecessary widgetset compilation requests to the user.

**Comment by makoivis** [comment]
**Comment by Henri Sara on 3 Nov 2009 14:01 UTC**
In [9605], avoid asking the user about building widgetsets when any widgetset build is running in the project (and some refactoring).

**Comment by makoivis** [comment]
**Comment by Henri Sara on 4 Nov 2009 07:02 UTC**
Mark widgetset as dirty on client side class modification in [9608].

**Comment by makoivis** [comment]
**Comment by Henri Sara on 4 Nov 2009 10:44 UTC**
Made widgetset compilation at publish to server synchronous in [9613].
This changeset also includes some progress reporting improvements/fixes.

**Comment by makoivis** [comment]
**Comment by Henri Sara on 4 Nov 2009 12:13 UTC**
Split the remaining part (WAR export) to #3648.

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:41 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 9 Sep 2014 08:39 UTC**

**Comment by hesara** [comment]
Duplicate of #161 (already closed)
