### ISSUE TITLE
The widgetset builder must use the project build path

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#20]
**Reported by Artur Signell on 22 Oct 2009 10:43 UTC**
Libraries and classes can be located anywhere on the build path thus the widgetset builder must use the build path.

**Comment by makoivis** [comment]
**Comment by Henri Sara on 2 Nov 2009 08:51 UTC**
First step: refactoring in [9561] to isolate the classpath construction and share logic with the old widgetset build launch creation.

**Comment by makoivis** [comment]
**Comment by Henri Sara on 2 Nov 2009 09:38 UTC**
Done in [9563].

**Comment by makoivis** [comment]
**Comment by Henri Sara on 4 Nov 2009 07:54 UTC**
With certain (many?) external libraries, this causes GWT compilation problems. Therefore, probably need to revert to not including all JARs on widgetset build path.

The problems may manifest themselves e.g. in the form of the exception
java.lang.NoSuchMethodError: org.eclipse.jdt.internal.compiler.lookup.ProblemReferenceBinding.closestReferenceMatch()Lorg/eclipse/jdt/internal/compiler/lookup/ReferenceBinding;

**Comment by makoivis** [comment]
**Comment by Henri Sara on 4 Nov 2009 12:05 UTC**
Cannot use project classpath as-is, the GWT compiler has problems with many external libraries.

In [9620], reverted to using only known good JARs in widgetset compiler classpath. If external JARs (other than those containing GWT modules) are needed on the client side, some solution for specifying them explicitly needs to be found.

**Comment by makoivis** [comment]
**Comment by Artur Signell on 7 Dec 2009 10:07 UTC**
For now all jars that are to be included in the widgetset must either:
- Contain a GWT module
- Contain a Vaadin add-on (which is a GWT module).

In other cases the classes need to be extracted (or added to a GWT module jar)

**Comment by makoivis** [comment]
**Comment by Artur Signell on 8 Apr 2010 05:27 UTC**
Closing this as the current version seems to work satisfactory. Create new tickets for any issues.

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:41 UTC**

**Comment by makoivis** [comment]
**Comment by Artur Signell on 28 Aug 2014 08:46 UTC**
Milestone Plug-in for Eclipse backlog deleted

**Comment by makoivis** [comment]
**Modified by Artur Signell on 9 Sep 2014 10:02 UTC**

**Comment by hesara** [comment]
Duplicate of #162 (already closed)
