### ISSUE TITLE
Document how to use OOPHM libraries with the widgetset builder

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#21]
**Reported by Artur Signell on 22 Oct 2009 10:47 UTC**
Until GWT 2.0 arrives we must provide documentation for how to use our OOPHM packages with the widgetset builder. This is very critical as OOPHM is the only way to debug widgets on certain platforms. It should be documented somewhere in the plugin where people find it, not hidden in a wiki.

**Comment by makoivis** [comment]
**Modified by Artur Signell on 22 Oct 2009 10:47 UTC**

**Comment by makoivis** [comment]
**Comment by Henri Sara on 30 Oct 2009 08:13 UTC**
The relevant wiki documentation to use as a starting point is in
- http://vaadin.com/wiki/-/wiki/Main/OOPHM%20Step%20by%20Step
- http://vaadin.com/forum/-/message_boards/message/79246#_19_message_79384

**Comment by makoivis** [comment]
**Comment by Henri Sara on 5 Nov 2009 07:20 UTC**
See also #3569.

**Comment by makoivis** [comment]
**Comment by Henri Sara on 6 Nov 2009 08:35 UTC**
In [9655], implemented together with #3023.

The messages should be reviewed and relevant documentation updated.

**Comment by makoivis** [comment]
**Modified by Artur Signell on 23 Nov 2009 14:44 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:41 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 9 Sep 2014 08:39 UTC**

**Comment by hesara** [comment]
Duplicate of #163 (already closed)
