### ISSUE TITLE
Refresh parent package when creating widgetset.gwt.xml

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#22]
**Reported by Artur Signell on 22 Oct 2009 10:49 UTC**
The parent package (NOT including sub packages) should be refreshed when a xyzWidgetSet.gwt.xml is created so it becomes visible in Eclipse.

**Comment by makoivis** [comment]
**Comment by Henri Sara on 29 Oct 2009 11:33 UTC**
Fixed in [9459].

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:42 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 9 Sep 2014 08:39 UTC**

**Comment by hesara** [comment]
Duplicate of #164 (already closed)
