### ISSUE TITLE
Add comments to the auto generated widgetset.gwt.xml

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#23]
**Reported by Artur Signell on 22 Oct 2009 10:50 UTC**
A generic comment section describing what the file is.

A comment before every added row telling why it is there i.e. what jar file contains it.

**Comment by makoivis** [comment]
**Modified by Artur Signell on 7 Dec 2009 09:59 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 15 Nov 2013 14:34 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:43 UTC**

**Comment by makoivis** [comment]
**Comment by Artur Signell on 28 Aug 2014 08:46 UTC**
Milestone Plug-in for Eclipse backlog deleted

**Comment by hesara** [comment]
Duplicate of #165 (already closed)
