### ISSUE TITLE
Old project compatibility

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#24]
**Reported by Artur Signell on 22 Oct 2009 11:09 UTC**
Updating old projects MUST work seamlessly. Current problems:
- Updating an old project to 6.2.0.nightly will cause it not to compile: "Select a widgetset file or a Vaadin project to compile". This even though the project is selected.
- Updating to 6.2.0.nightly before upgrading to the new plugin version will not enable the Vaadin builder for the project. The build button should check if the Builder is enabled and if it is not, enable it. Also it should upgrade the facet version to 1.0 to avoid future problems.

**Comment by makoivis** [comment]
**Comment by Henri Sara on 28 Oct 2009 14:02 UTC**
In [facet version is automatically upgraded and widgetset builder nature added when making changes in Project properties -> Vaadin and when clicking on the "build widgetset" button.

Depends on [9430](9431],) in Vaadin 6.2.0 for automatic new widgetset creation to work.

More testing is required.

**Comment by makoivis** [comment]
**Comment by Henri Sara on 4 Nov 2009 10:48 UTC**
Considered done - any further issues should be reported separately.

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:41 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 9 Sep 2014 08:39 UTC**

**Comment by hesara** [comment]
Duplicate of #166 (already closed)
