### ISSUE TITLE
Nightly version list is too long

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#25]
**Reported by Artur Signell on 22 Oct 2009 11:19 UTC**
The nightly version list is confusing as it contains too many items. Filtering out all but the latest nightly by default would be a way of shortening the list. It should still be possible to find an older nightly version though.

**Comment by makoivis** [comment]
**Comment by Henri Sara on 5 Nov 2009 14:33 UTC**
The version numbering of 6.2 nightly builds changed in late October 2009, in the middle of the 6.2-series. An additional numerical component was added in nightly build version numbers to better support Maven snapshots.

On the download server, and thus also in the download list, e.g. 6.2.0-nightly-20091102-c9584 gets sorted after 6.2.nightly-20091010-c9195 . Within each build type and series, anything with a number after the second dot comes after anything with some other character at that position.

This non-intuitive build order only affects the 6.2 series.

Other than this issue, the most recent nightly is shown first, and the user rarely needs to look further than that as all other kinds of builds come before it. The user could be interested also in the latest nightly build of an older branch, though. All older nightly builds are listed so it is possible to access them.

Other parts of the system (primarily the Eclipse filtered list dialog) that could disrupt the order have already been modified.

An explicit sort within each directory (in DownloadUtils.filterVaadinVersions()), taking this 6.2 nightly build peculiarity into account, could help.

**Comment by makoivis** [comment]
**Comment by Henri Sara on 6 Nov 2009 11:05 UTC**
Fixed order for the download dialog and for the version combo in [9661].

Note that the order used in the download dialog is by release type, whereas the locally downloaded version list shows more recent versions first with the exception of final releases of each branch being shown first.

In the download dialog, the user can filter the list by typing in the filter field.

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:42 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 9 Sep 2014 08:39 UTC**

**Comment by hesara** [comment]
Duplicate of #167 (already closed)
