### ISSUE TITLE
After widgetset builder visit, JAR files in WebContent lib cannot be deleted

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#26]
**Reported by Henri Sara on 22 Oct 2009 13:50 UTC**
The Eclipse plugin widgetset builder scans changed JARs in the project, opening them but never closing them. Thus, the files stay locked and cannot be deleted at least on Windows.

**Comment by makoivis** [comment]
**Comment by Henri Sara on 22 Oct 2009 13:53 UTC**
Fixed in [9309].

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:42 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 9 Sep 2014 08:39 UTC**

**Comment by hesara** [comment]
Duplicate of #168 (already closed)
