### ISSUE TITLE
Incorrect version number for Book of Vaadin eclipse plugin

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#309]
**Reported by Joonas Lehtinen on 7 Sep 2010 09:32 UTC**
Current eclipse plugin (as of today from experimental plugin distro) says:

Book of Vaadin

Vaadin 6.4

Vaadin Ltd

Marko Grnroos

Vaadin Framework 6.2.0

Copyright  2000-2010 Vaadin Ltd

All rights reserved.
2010-09-03

So the contents is updated, but version number not. The same 6.2.0 is also shown when downloading plugin

Migrated-From: https://dev.vaadin.com/ticket/5552

**Comment by makoivis** [comment]
**Modified by Artur Signell on 7 Sep 2010 10:59 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 15 Nov 2013 14:34 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:43 UTC**

**Comment by makoivis** [comment]
**Comment by Artur Signell on 28 Aug 2014 08:46 UTC**
Milestone Plug-in for Eclipse backlog deleted

**Comment by hesara** [comment]
Book of Vaadin as Eclipse plug-in has been retired a long time ago.
