### ISSUE TITLE
The unnecessary extra level in the project preferences page should be removed

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#33]
**Reported by Jonatan Kronqvist on 27 Oct 2009 12:47 UTC**
Currently the eclipse plugin has a main view in the project preferences which just states to open the tree to access settings. When opening the tree, however, there is only one view with settings (which version of Vaadin to use).

These should, IMO, be merged to allow for a better user experience.

**Comment by makoivis** [comment]
**Comment by Henri Sara on 27 Oct 2009 12:54 UTC**
Removed extra level in [9408] and moved version selection to the main project property page.

Future settings can be added on the main page or on new subpages.

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:42 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 9 Sep 2014 08:39 UTC**

**Comment by hesara** [comment]
Duplicate of #175 (already closed)
