### ISSUE TITLE
Projects not located in workspace dir cannot be compiled

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#34]
**Reported by Matti Tahvonen on 29 Oct 2009 08:58 UTC**
If project is in workspace, but project directory does not locate in workspace folder, widgetset compilation does not work. Utility method gives invalid paths as classpath.

**Comment by makoivis** [comment]
**Comment by Henri Sara on 29 Oct 2009 09:39 UTC**
Fixed in [9450]: do not assume that classpath entries are inside the workspace.

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:41 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 9 Sep 2014 08:39 UTC**

**Comment by hesara** [comment]
Duplicate of #176 (already closed)
