### ISSUE TITLE
Generate @import statement for add-on themes

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#340]
**Reported by Marko Gronroos on 18 Nov 2010 08:34 UTC**
When the user adds an add-on Jar to a Vaadin project, the add-on can include a theme. The project theme or themes should be modified to @import this add-on theme.

I think there are two cases:
- Theme add-on, where the @import of a built-in theme needs to be replaced with @import of the add-on theme that is based on a built-in theme (it imports a built-in theme).
- Composite component add-on that includes themeing for just one component, in which case the @import statement needs to be just added, not replacing any existing @import

Migrated-From: https://dev.vaadin.com/ticket/6006

**Comment by makoivis** [comment]
**Modified by Artur Signell on 15 Nov 2013 14:34 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:42 UTC**

**Comment by makoivis** [comment]
**Comment by Artur Signell on 28 Aug 2014 08:46 UTC**
Milestone Plug-in for Eclipse backlog deleted

**Comment by hesara** [comment]
This has been handled by the AddonStylesBuilder builder and/or the Maven goal update-theme for a long time already. They update the automatically managed file addons.scss .
