### ISSUE TITLE
Eclipse plug-in should default to Java 1.5 Facet

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#36]
**Reported by Jani Laakso on 3 Nov 2009 12:57 UTC**
Users should not be required to downgrade their Facet from 1.6 to 1.5 just to make class compatibility from 1.6 to 1.5. 

Could "Create Vaadin Project" with Portlet option on default to 1.5 instead of 1.6?

**Comment by makoivis** [comment]
**Modified by Jani Laakso on 3 Nov 2009 22:00 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 5 Nov 2009 06:48 UTC**

**Comment by makoivis** [comment]
**Comment by Henri Sara on 5 Nov 2009 13:52 UTC**
The Vaadin plugin currently only specifies that the Java facet version has to be at least 5.0. The actual facet version used depends on the configuration of Eclipse -  Web Tools Platform behind the wizard decides the Java facet version to use based on the workspace-level compiler class compatibility options, as it should.

Thus, if you have configured your Eclipse defaults to be compatible with developing anything for Liferay, the correct facet version should be automatically selected, at least with recent Eclipse and WTP versions.

The problem arises from the fact that many developers have Eclipse configured to produce output that is only compatible with JRE 1.6, but run Liferay on the default JRE bundled with it. Other portals and other deployment environments typically do not have this problem.

**Comment by makoivis** [comment]
**Comment by Artur Signell on 12 Mar 2010 12:45 UTC**
I do not think we should force the java version to one that has already reached end of life (1.5). As Henri says we only require a minimum version and if you use a Liferay distribution based on 1.5 you need to take care that the Eclipse project java version is the same, just as in any project. (Apparently not all Liferay distributions are based on JDK 1.5)

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 Mar 2010 12:45 UTC**

**Comment by makoivis** [comment]
**Modified by Henri Sara on 5 Oct 2010 10:46 UTC**

**Comment by makoivis** [comment]
**Comment by Henri Sara on 5 Oct 2010 10:48 UTC**
In [15409], provide project configuration alternatives for Java5 and Java6, Java5 as default.

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:42 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 9 Sep 2014 08:39 UTC**

**Comment by hesara** [comment]
Duplicate of #177 (already closed)
