### ISSUE TITLE
Creating new Widget not possible without already created Widgetset

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#37]
**Reported by Jani Laakso on 3 Nov 2009 21:56 UTC**
People may try to create Widget before Widgetset and this leads to an window containing red exclamation mark without any error message.

Fixing error message seems correct solution.

**Comment by makoivis** [comment]
**Modified by Jani Laakso on 3 Nov 2009 21:57 UTC**

**Comment by makoivis** [comment]
**Comment by Matti Tahvonen on 4 Nov 2009 08:34 UTC**
This wont be an issue with 6.2 and corresponding plugin version. Widgetsets are created automatically.

**Comment by makoivis** [comment]
**Comment by Henri Sara on 8 Dec 2009 13:29 UTC**
Fixed in [10200] with a status message when a widgetset is needed and none exists in project.1

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:43 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 9 Sep 2014 08:39 UTC**

**Comment by hesara** [comment]
Duplicate of #178 (already closed)
