### ISSUE TITLE
The widgetset should be built when exporting a WAR

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#40]
**Reported by Henri Sara on 4 Nov 2009 12:12 UTC**
The user should be asked if he wants to recompile the widgetset when exporting a WAR file and the widgetset is dirty.

This was split off from #3573, where a similar feature was added when publishing a project to a server.

**Comment by makoivis** [comment]
**Comment by Henri Sara on 10 Dec 2009 07:10 UTC**
Implemented in [10212].

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:42 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 9 Sep 2014 08:39 UTC**

**Comment by hesara** [comment]
Duplicate of #181 (already closed)
