### ISSUE TITLE
Use human-readable labels for GWT compilation style selection

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#42]
**Reported by Joonas Lehtinen on 6 Nov 2009 12:48 UTC**
Now there are three JavaScipt styles to chosse from in the eclipse plugin. Maybe we should call the first one OBFUSCATED instead of OBF (Even though GWT calls it OBF). Why? OBF might be quite confusing if you are not familiar with GWT compiler command line options already (and I am sure, most of the users are not).

**Comment by makoivis** [comment]
**Comment by Henri Sara on 6 Nov 2009 13:02 UTC**
Fixed in [9664]: use more human readable labels for all compilation styles.

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:43 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 9 Sep 2014 08:39 UTC**

**Comment by hesara** [comment]
Duplicate of #183 (already closed)
