### ISSUE TITLE
Plugin should not ask for widgetset recompilations for server-side changes

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#43]
**Reported by Joonas Lehtinen on 6 Nov 2009 16:25 UTC**
Currently all changes cause "do you want to recompile widgetset". This makes development miserable.

Also it should be possible to turn off the whole change detection when using OOPHM.

**Comment by makoivis** [comment]
**Comment by Artur Signell on 9 Nov 2009 08:09 UTC**
- Add feature for deactivating automatic asking/compilation of widgetset
- If simple enough, check if @ClientWidget annotation has changed and only then ask for recompilation (when editing server side classes)
- If not possible, user must manually recompile after changing annotation

**Comment by makoivis** [comment]
**Comment by Henri Sara on 9 Nov 2009 12:15 UTC**
The following changes trigger the automatic recompilation request:
- the addition or change of a JAR containing Vaadin widgetset metadata
- the removal of (currently any) JAR
- a modification to a GWT module (.gwt.xml)
- a modification to a client side class (somewhere inside a .client. package whose parent has a GWT module)
- a modification to a class with the ClientWidget annotation

The first two trigger an immediate request, whereas the last three only flag the widgetset as dirty and the widgetset recompilation request is shown at build/publish time.

In addition, the request is triggered for a project which has a dirty widgetset when
- publishing a project to a server
- changing Vaadin related properties on the project property page

Automatic immediate publishing to server while editing a class with the annotation can make the question appear frequently.

In [9686]:
- provided an option to suspend such recompilation requests
  - in project properties
  - in the "Compile widgetset?" dialog
- disabled automatic recompilation on server side class content change
  - ideally, should mark as dirty if and only if the annotation has changed

**Comment by makoivis** [comment]
**Modified by Henri Sara on 9 Nov 2009 12:18 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:42 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 9 Sep 2014 08:39 UTC**

**Comment by hesara** [comment]
Duplicate of #184 (already closed)
