### ISSUE TITLE
The details of the vaadin group in the eclipse plugin install dialog reports wrong version

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#508]
**Reported by John Ahlroos on 18 Feb 2013 13:52 UTC**
When installing or updating the plugin the "Install" dialog when clicking on the "Vaadin" group shows details as "Vaadin 0.0.0". The details should either be a bit more descriptive or the version number should be correct.

Migrated-From: https://dev.vaadin.com/ticket/11066

**Comment by makoivis** [comment]
**Modified by Artur Signell on 15 Nov 2013 14:04 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 08:40 UTC**

**Comment by makoivis** [comment]
**Comment by Artur Signell on 28 Aug 2014 08:46 UTC**
Milestone Plug-in for Eclipse backlog deleted

**Comment by hesara** [comment]
This has been fixed at least in the 2.3 series of the Eclipse plug-in, probably already long before them.
