### ISSUE TITLE
could not open design view in eclipse

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#582]
**Reported by fever on 12 Feb 2014 23:10 UTC**
Vaadin Plugin for eclipse 2.2.0.201312051010

I was working with Vaadin composite 2 days ago and everything was running fine. The was composite drag and drop from the design view and was added in the UI file and then added on tomcat 7 server, everything was ok.

From yesterday everytime I try to open the design tab of that java composite file, eclipse shut itself down and gave me the attached error file.

Could you please let me know what has changed recently and why did it happen? I tried to un-install the Vaadin plug-in for eclipse and re-install, eclipse still shut itself down everytime I try to click on the design tab.

Migrated-From: http://dev.vaadin.com//ticket/13333

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 08:41 UTC**

**Comment by samie** [comment]
Visual Designer deprecated, please refer to Vaadin Designer.
