### ISSUE TITLE
Toolbar icon does not relate to Vaadin

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#587]
**Reported by demobooth on 28 Apr 2014 02:24 UTC**
With current cog wheel icon it is unintuitive to find the Vaadin related actions (theme and widgetset compilation). Vaadin-related icon suggested.

Migrated-From: http://dev.vaadin.com//ticket/13656

**Comment by makoivis** [comment]
**Comment by Jouni Koivuviita on 28 Apr 2014 12:13 UTC**
Agreed, I noticed the same thing just a few days ago. It was a poor decision to remove the Vaadin logo from the icon.

I will try to reserve some time to design new icons.

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 08:41 UTC**

**Comment by samie** [comment]
This has been changed since plugin version 3.0.
