### ISSUE TITLE
Update Eclipse plugin facet version

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#6]
**Reported by Henri Sara on 1 Oct 2009 10:11 UTC**
The facet version of the Vaadin facet should be 1.0, not 0.1 .

The plugin should support changing the facet version for old projects, and new projects should automatically use the new version.

The old version 0.1 can be removed (leading to warnings on the project facets page but full functionality) or still included in the plugin.

**Comment by makoivis** [comment]
**Comment by Henri Sara on 1 Oct 2009 10:59 UTC**
Changed version to 1.0 in [9004].

Old version was removed from the plugin. Users can update the facet version on the project properties -> project facets page.

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:42 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 9 Sep 2014 08:39 UTC**

**Comment by hesara** [comment]
Duplicate of #147 (already addressed)
