### ISSUE TITLE
Vaadin logo not shown in Eclipse plug-in icon

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#601]
**Reported by Leif Astrand on 17 Sep 2014 06:26 UTC**
It is really hard to find the right button in the Eclipse toolbar since it's just some cogwheels with nothing indicating that it has anything to do with Vaadin.

Migrated-From: http://dev.vaadin.com//ticket/14678

**Comment by makoivis** [comment]
**Comment by Jouni Koivuviita on 23 Oct 2014 10:32 UTC**
Mockups for new icon designs. Icons for the "New" wizards should be aligned at the same time, but I didn't draw mockups of those at this point, waiting for comments on the initial ideas first.

**Comment by makoivis** [comment]
**Modified by Jouni Koivuviita on 23 Oct 2014 10:32 UTC**

**Comment by makoivis** [comment]
**Comment by Leif Astrand on 24 Apr 2015 07:55 UTC**
Hi, this ticket has been in the accepted state without any updates for a long time. Is someone still working on this?

If not, then please select "no longer working on this" in the Actions box below so that anyone else interested in investigating can know there's nobody else working on it.

**Comment by makoivis** [comment]
**Modified by Jouni Koivuviita on 24 Apr 2015 08:12 UTC**

**Comment by samie** [comment]
Icons have been changed in version 3.0
