### ISSUE TITLE
Vaadin Eclipse Plugin license shows 2013, not 2014

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#612]
**Reported by enver on 4 Dec 2014 11:25 UTC**

Summary says it all -- just updated my Plugin today and the
license said (C) Vaadin 2000(?) - 2013
Should surely read "2014".

Migrated-From: http://dev.vaadin.com//ticket/15324

**Comment by makoivis** [comment]
**Comment by Artur Signell on 23 Sep 2015 09:27 UTC**
Maybe 2015 would be more appropriate? :)

**Comment by elmot** [comment]
It shows 2016 in version 3.0.0.beta3
