### ISSUE TITLE
Deprecate Vaadin Composite

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#621]
**Reported by John Ahlroos on 3 Mar 2015 08:51 UTC**
The Vaadin Composite should be deprecated in favor of a Vaadin Design by marking the Vaadin Composite as deprecated in eclipse New->Vaadin Composite list.

Migrated-From: http://dev.vaadin.com//ticket/16986

**Comment by makoivis** [comment]
**Modified by John Ahlroos on 3 Mar 2015 08:54 UTC**

**Comment by makoivis** [comment]
**Modified by John Ahlroos on 3 Mar 2015 08:54 UTC**

**Comment by johndevs** [comment]
This has already been done and can be closed.

**Comment by hesara** [comment]
Already done in 3.0 beta1 or possibly one of the alphas.
