### ISSUE TITLE
License text should be summarized as "Apache 2" and not "Copyright 2010"

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#622]
**Reported by Artur Signell on 4 Mar 2015 15:15 UTC**
When you install the Vaadin plug-in, you must accept the license. Because the first text row is "Copyright 2010-2013 Vaadin Ltd.", the summary also shows "Copyright 2010-2013 Vaadin Ltd."

Migrated-From: http://dev.vaadin.com//ticket/17018

**Comment by samie** [comment]
Duplicated of #630
