### ISSUE TITLE
Remove "Vaadin Editor"

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#628]
**Reported by Artur Signell on 7 Sep 2015 07:41 UTC**
If you right click and select "open" for the Java part of a design, you get the option to open it in "Vaadin Editor" with the Vaadin logo. 

Doing this and selecting the "Design" tab causes "Could not open design view: Failed to find or parse visually editable class caused by Not an editable CustomComponent"

Migrated-From: http://dev.vaadin.com//ticket/18801

**Comment by makoivis** [comment]
**Modified by Artur Signell on 7 Sep 2015 07:41 UTC**

**Comment by makoivis** [comment]
**Modified by denis on 9 Sep 2015 09:45 UTC**

**Comment by makoivis** [comment]
**Comment by John Ahlroos on 14 Sep 2015 13:55 UTC**
Why is this in the Designer backlog? 

This needs to be fixed in the Vaadin Eclipse Plugin which adds itself as a Java editor to all Java files. The designer can't do anything about that.

**Comment by hesara** [comment]
The old Visual Editor plug-in has now been moved to a separate legacy feature and thus isn't installed automatically with the main plug-in.
