### ISSUE TITLE
Cannot run simple Vaadin Program on Eclipse

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#635]
**Reported by shagg on 13 Oct 2015 14:21 UTC**
I am trying to run the Vaadin program on Eclipse using Tomcat Server but while doing so its throwing the following error:

INFO: Requested resource [not found from filesystem or through class loader. Add widgetset and/or theme JAR to your classpath or add files to WebContent/VAADIN folder.
com.vaadin.server.VaadinServlet serveStaticResourcesInVAADIN
INFO: Requested resource [/VAADIN/themes/valo/valo.scss](/VAADIN/widgetsets/com.vaadin.DefaultWidgetSet/com.vaadin.DefaultWidgetSet.nocache.js]) not found from filesystem or through class loader. Add widgetset and/or theme JAR to your classpath or add files to WebContent/VAADIN folder.

and 

also is giving a pop up saying "Failed to load the widget: ./../VAADIN/widgetsets/com.vaadin.DefaultWidgetSet/com.vaadin.DefaultWidgetSet.nocache.js?1444745704670".

Please help me out resolving this error.

Thanks

Migrated-From: http://dev.vaadin.com//ticket/19127

**Comment by makoivis** [comment]
**Modified by shagg on 13 Oct 2015 14:24 UTC**

**Comment by samie** [comment]
Most likely reason for this is that dependencies for **vaadin-themes** ja **vaadin-client-compiled** are missing. They should be listed in the ivy.xml by default: 

```
    <dependency org="com.vaadin" name="vaadin-themes" rev="&vaadin.version;" />
    <dependency org="com.vaadin" name="vaadin-client-compiled" rev="&vaadin.version;" />
```

They should be automatically resolved and downloaded, but you can manually install them by opening  context menu on the project and choose Ivy -> Resolve. Also 'clean all caches' might help, if there was problem during download.
