### ISSUE TITLE
Compile theme and widgetset using Maven in Maven projects

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#639]
**Reported by Henri Sara on 27 Jan 2016 09:21 UTC**
When working with a Maven project, the Eclipse plug-in should use the appropriate Maven goals to compile the theme and the widgetset rather than doing it the way it is done for Ivy projects.

Migrated-From: http://dev.vaadin.com//ticket/19521

**Comment by makoivis** [comment]
**Comment by Henri Sara on 27 Jan 2016 09:32 UTC**
Partial implementation under review at https://dev.vaadin.com/review/6239 .

**Comment by makoivis** [comment]
**Comment by Henri Sara on 27 Jan 2016 09:56 UTC**
See review comments - in gerrit but requires some more changes

**Comment by hesara** [comment]
Resolved by #3
