### ISSUE TITLE
Addon Styles Builder fails on Maven project import

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#642]
**Reported by elmot on 10 Feb 2016 09:16 UTC**
Problematic maven archetypes:
vaadin-archetype-application-example(-production subproject)
vaadin-archetype-application-multimodule(-production subproject)
While importing maven project, eclipse reports problems:

Errors occurred during the build.
Errors running builder 'Addon Styles Builder' on project 'app-example-production'.
Unable to locate WebContent folder. Ensure the project is a dynamic web project.
Unable to locate WebContent folder. Ensure the project is a dynamic web project.
Errors running builder 'Addon Styles Builder' on project 'mmodule-production'.
Unable to locate WebContent folder. Ensure the project is a dynamic web project.
Unable to locate WebContent folder. Ensure the project is a dynamic web project.

It look like Addon Styles Builder is activated for projects which do not require it.

Migrated-From: http://dev.vaadin.com//ticket/19581

**Comment by hesara** [comment]
Sometimes the builder (or the related nature) is even activated for projects unrelated with Vaadin. It should not do anything when active on a non-Vaadin project (if already there), and should not be added for such projects.

**Comment by hesara** [comment]
This should be fixed in 3.0.0.beta1 (on the experimental update site) so that the builder is not added/used for Maven projects and non-Vaadin projects. If there are still cases where it fails, please open a ticket with details.
