### ISSUE TITLE
Part of notification icon missing in Eclipse tray

### ISSUE THREAD

**Issue by johannesh2** [vaadin/eclipse-plugin-legacy#666]
The notification icon is showing only partly. Top and bottom of the Vaadin logo is cut.

Version: Mars.2 Release (4.5.2)
Plugin 2.3.7
![eclipse-plugin-screenshot](https://cloud.githubusercontent.com/assets/1398470/13638277/398cfb34-e614-11e5-9347-ba285d9c29c8.PNG)

**Comment by elmot** [comment]
What the OS are you using?

**Comment by johannesh2** [comment]
Windows 10

**Comment by johannesh2** [comment]
Still happening with 3.0.0.beta1
