### ISSUE TITLE
Plugin does not create latest-version archetype

### ISSUE THREAD

**Issue by samie** [vaadin/eclipse-plugin-legacy#698]
The 'experimental' plug-in with Maven support creates Vaadin 7.6.5
projects even though it knows 7.6.6 is out from the web.
That's stupid -- creating something out-of-date then moaning that it
is.

**Comment by samie** [comment]
This might have been a temporary thing, but we'll check.

**Comment by hesara** [comment]
Fixed in the metadata on vaadin.com/download
