### ISSUE TITLE
Application select in new Widgetset wizard shows widgetsets from other projects

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#7]
**Reported by Artur Signell on 1 Oct 2009 13:05 UTC**
None

**Comment by makoivis** [comment]
**Comment by Artur Signell on 1 Oct 2009 13:07 UTC**
"Package name" and "name" can also come from the wrong project.

**Comment by makoivis** [comment]
**Comment by Henri Sara on 2 Oct 2009 11:26 UTC**
This happens when Application subclasses from other projects are open in editors - Eclipse getSubClasses gets the classes from the active project AND those open in editors.

Fixed in [9039].

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:42 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 9 Sep 2014 08:39 UTC**

**Comment by hesara** [comment]
Duplicate of #148 (already closed/released)
