### ISSUE TITLE
Remove Vaadin Framework 6 support

### ISSUE THREAD

**Issue by Artur-** [vaadin/eclipse-plugin-legacy#712]
Just disable it. Do not try to make it clean, just get it done.
- remove all vaadin 6 related wizards from plugin.xml
- remove all vaadin 6 related global configuration options from preferences page
- remove Vaadin 7 Ivy project wizard
- remove notifications about version updates for Ivy projects

**Comment by hesara** [comment]
Removing nightly build checks in #722 .
Disabling wizards and presets in #723 .

Remaining work: configuration page cleanup, additional testing.

**Comment by hesara** [comment]
Remaining work: preferences page and facet install

**Comment by hesara** [comment]
#735 addressed property pages and some more.
Remaining work: facet install, facet versions, testing.

**Comment by hesara** [comment]
Decided not to remove the facet versions now to make sure old Vaadin 7 projects continue working. Performed some testing of installing the Vaadin facet on Dynamic Web Project creation as well as after one has been created.
