### ISSUE TITLE
Create an update site for 3.0

### ISSUE THREAD

**Issue by Artur-** [vaadin/eclipse-plugin-legacy#713]
The same version which is currently at https://vaadin.com/eclipse (i.e. https://github.com/vaadin/eclipse-plugin/tree/3.0) should be copied to 
https://vaadin.com/eclipse/4.4

The web site text at vaadin.com/eclipse should be updated to say
- Eclipse 4.5 and newer: http://vaadin.com/eclipse
- Eclipse 4.4: http://vaadin.com/eclipse/4.4

**Comment by johndevs** [comment]
Please remember that http://vaadin.com/eclipse hosts both the Vaadin eclipse plugin as well as the Designer and is automatically built by http://r2d2.devnet.vaadin.com/viewType.html?buildTypeId=EclipseUpdateSite_BuildUpdateSite.

**SO COPYING THE UPDATE SITE IS NOT AN OPTION**

The actual eclipse plugin update site is hosted at https://vaadin.com/eclipse/internal/core so maybe create another internal site and update the links in https://dev.vaadin.com/review/gitweb?p=update-site.git;a=blob;f=pom.xml;h=508439181d00239832d39a2ce2e953e0d765120e;hb=refs/heads/master

**Comment by Artur-** [comment]
Why is copying the update site not an option?

**Comment by Artur-** [comment]
We should probably do this at a point when Designer also drops Luna support (1.2?) so that we can freeze the previous version as eclipse/4.4 and make all new versions for the main site

**Comment by johndevs** [comment]
> Why is copying the update site not an option?

I don't see why you want to copy the main update site which is auto-generated? 

If you want to preserve the old Vaadin Eclipse plugin then you want to copy https://vaadin.com/eclipse/internal/core which only hosts the plugin and not designer into https://vaadin.com/eclipse/4.4. That way the user can install the old plugin but still use the newest version of the Designer from the main update site.

> We should probably do this at a point when Designer also drops Luna support (1.2?)

Why would we drop Luna support, what benefit would it have?

**Comment by pleku** [comment]
After this is done, someone from marketing should update the eclipse marketplace metadata. Remember to notify @samie or someone else from marketing.

**Comment by Legioth** [comment]
The easiest way to get going with the Framework 8 support is to create a copy.

The Designer team is still free to replace that copy with a dynamically built version if they consider it important to be able to use newer Designer versions with the legacy version of the plugin.

**Comment by Legioth** [comment]
But we should wait for Designer 1.2 before creating the final copy.

**Comment by hesara** [comment]
Copied relevant parts of current site to 4.4, and copied internal/core to internal/core-4.4 that can still be used in the combining build to update the 4.4 site when a new designer version is available and should be published also for Luna. Will do new development in internal/core-testing and experimental, so internal/core-4.4 can be considered a back-up until we start publishing FW8 features.

Will inform marketing regarding Eclipse Marketplace after testing.

**Comment by hesara** [comment]
Marketing informed regarding Eclipse marketplace.
