### ISSUE TITLE
Update version and version support

### ISSUE THREAD

**Issue by Artur-** [vaadin/eclipse-plugin-legacy#715]
The plug-in version should be 4.0

It should support Eclipse Neon and Mars

**Comment by pleku** [comment]
There might be changes required between targeted eclipse versions, might require dependency updates etc.

**Comment by hesara** [comment]
Somewhat related changes: #718 and #719.
The version of the plug-in being built comes from the CI rather than the project, so no project change for that.

Remaining work related to this: test with Mars, update repository list (luna -> mars) in top level POM.

**Comment by hesara** [comment]
Quick tests done with Mars. Change of repository in #720.
