### ISSUE TITLE
Current version of plugin not visible in 2018.12 marketplace

### ISSUE THREAD

**Issue by ripla** [vaadin/eclipse-plugin-legacy#755]
With the new release of Eclipse 2018.12, the marketplace shows an old version of the Vaadin Eclipse plugin. Newest version atm. is 4.0.2, but the marketplace shows 2.3.2.

**Comment by blekione** [comment]
Workaround for this is to manually add link http://vaadin.com/eclipse/ to "Install new software..." window in Eclipse. After that you can install the latest version of plugin from it.

**Comment by ripla** [comment]
Fixed in new Eclipse versions.
