### ISSUE TITLE
New project tech stack option names should be the same as on start page

### ISSUE THREAD

**Issue by johannesh2** [vaadin/eclipse-plugin-legacy#791]
The options for Base Starter for Vaadin Flow
* spring -> Spring Boot
* javaee -> CDI and Java EE
* plain-java -> Plain Java Servlet

The option for Simple App
* plain-java -> Java

**Comment by samie** [comment]
"Java EE" is "Jakarta EE"

**Comment by szolo** [comment]
@samie we're not hardcoding this. Tech stack label are received from the vcom API.

**Comment by samie** [comment]
Alright! That should be easy fix then.
