### ISSUE TITLE
Track notifications

### ISSUE THREAD

**Issue by ripla** [vaadin/eclipse-plugin-legacy#795]
In order to determine how useful notifications are and how we could further develop them, we need to get analytics data. We should track 

* When a notification is shown
* When the link is clicked
* When the notification is closed

**Comment by tanbt** [comment]
Also, add UTM parameters for links in the notification.
vaadin.com/blog/something/?`utm_source=eclipse&utm_medium=notification&utm_campaign=eclipse_notifications`

We would like to see in GA if a user came from a link in those notifications.

**Comment by tanbt** [comment]
Test tracking for UTM link clicks:

![image](https://user-images.githubusercontent.com/4935326/66829321-cf455280-ef5b-11e9-93f5-511b912d183f.png)

**Comment by tanbt** [comment]
Test tracking in Amplitude using my testing chart:
https://analytics.amplitude.com/vaadin/chart/wvmd0mh
