### ISSUE TITLE
New Vaadin 10+ project ignores Eclipse proxy settings

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/eclipse-plugin-legacy#798]
If you're behind a proxy, "New Vaadin 10+ project" will fail with the error "Unable to fetch information about available starters". This happens even if you have configured the Eclipse proxy settings correctly because `fetchStarters()` does not take the proxy configuration into account.

**Comment by szolo** [comment]
Also reported here https://vaadin.com/forum/thread/18104173/vaadin-10-project-unable-to-fetch-information-about-available-starters.

**Comment by Peppe** [comment]
Should be fixed via https://github.com/vaadin/designer/issues/2235
