### ISSUE TITLE
Plugin has conflict with latest version of Maven Eclipse plugin when using 2022-09

### ISSUE THREAD

**Issue by TatuLund** [vaadin/eclipse-plugin-legacy#807]
Installation complains dependency conflict

![image](https://user-images.githubusercontent.com/14309836/192992876-1e106adc-e741-488a-b123-66806709064a.png)

If you allow installation to autofix, it will remove the maven integration without installing a new one

![image](https://user-images.githubusercontent.com/14309836/192992898-b8d5f13c-d598-4190-9b22-526a035acf92.png)

**Comment by giacomoarru** [comment]
+1
same issue here

**Comment by abryantsev** [comment]
+1

**Comment by rgtodd** [comment]
+1

**Comment by abryantsev** [comment]
+1

**Comment by plouwbeond** [comment]
+1

**Comment by mo-jo** [comment]
Similar here.

Naked fresh eclipse-jee-2022-09-R-win32-x86_64.zip, also missing dependencies as osgi.bundle and mylyn.commons...

**Comment by szolo** [comment]
Hello, we are targeting to release a new Vaadin Eclipse plugin version which will address this problem next week. Thank you!

**Comment by szolo** [comment]
Good day, now Maven integration from IDE will be used, no specific version hardcoded. **4.1.7** is available at https://vaadin.com/eclipse update site and Marketplace, feel free to give it a try.
