### ISSUE TITLE
Plugin cannot not install on Eclipse 2022-06

### ISSUE THREAD

**Issue by plouwbeond** [vaadin/eclipse-plugin-legacy#808]
![image](https://user-images.githubusercontent.com/29735427/193251337-86b478e6-dd6a-4d87-b37c-253ec0b4ff03.png)

Error:
Cannot complete the provisioning operation.  Please change your selection and try again. See below for details.

Details:
Cannot complete the install because one or more required items could not be found.
  Software being installed: Vaadin Plug-in for Eclipse 4.1.6 (com.vaadin.integration.eclipse.feature.group 4.1.6)
  Missing requirement: Vaadin Plug-in for Eclipse 4.1.6 (com.vaadin.integration.eclipse 4.1.6) requires 'osgi.bundle; org.eclipse.mylyn.commons.workbench 0.0.0' but it could not be found
  Cannot satisfy dependency:
    From: Vaadin Plug-in for Eclipse 4.1.6 (com.vaadin.integration.eclipse.feature.group 4.1.6)
    To: org.eclipse.equinox.p2.iu; com.vaadin.integration.eclipse [4.1.6,4.1.6]

**Comment by plouwbeond** [comment]
Found workaround to add the Software Site for Mylyn

https://download.eclipse.org/mylyn/releases/latest

![image](https://user-images.githubusercontent.com/29735427/193252153-36ec773d-8b0b-4721-87f0-f536d5598a22.png)

**Comment by szolo** [comment]
Hello, we are targeting to release a new Vaadin Eclipse plugin version which will address this problem next week. Thank you!

**Comment by szolo** [comment]
Good day, **4.1.7** is available at https://vaadin.com/eclipse update site and Marketplace, feel free to give it a try.
